# -*- coding: utf-8 -*-
"""1부.4장 주요 시각화 그래프.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KzD2kLUG4gcnDKFX_G9TF03ig4WQa5Y0

# 노션링크(그래프 설명): https://www.notion.so/1-Chapter4-b503c72f5b234d22bfbb3daddf70323a?source=copy_link
"""

import seaborn as sns
titanic =sns.load_dataset('titanic')

titanic.head()

"""#1. 수치형 데이터 시각화

### histplot
"""

sns.histplot(data=titanic,x='age')

sns.histplot(data=titanic,x='age',bins=10)

sns.histplot(data=titanic,x='age',hue='alive')

sns.histplot(data=titanic,x='age',hue='alive',multiple='stack')

"""### kdeplot
- 히스토그램을 매끄러운 곡선으로 연결한 그래프
"""

sns.kdeplot(data=titanic, x='age')

sns.kdeplot(data=titanic, x='age',hue='alive',multiple='stack')

"""###displot"""

sns.displot(data=titanic,x='age')

sns.displot(data=titanic,x='age',kind='kde')

sns.displot(data=titanic,x='age',kde=True)

"""### rugplot"""

sns.kdeplot(data=titanic, x='age')
sns.rugplot(data=titanic, x='age')

"""#2. 범주형 데이터 시각화

### barplot
"""

sns.barplot(x="class",y="fare",data=titanic)

"""- 원래는 평균값을 나타내지만 estimator= (np.median,np.max,np.min) 등을 통해 바꿀 수 있다.

### pointplot
"""

sns.pointplot(x="class",y="fare",data=titanic)

"""### boxplot"""

sns.boxplot(x="class",y="age",data=titanic)

"""### violinplot"""

sns.violinplot(x="class",y="age",data=titanic)

sns.violinplot(x="class",y="age",hue="sex",data=titanic)

sns.violinplot(x="class",y="age",hue="sex",data=titanic,split=True)

"""### countplot"""

sns.countplot(x="class", data=titanic)

sns.countplot(y="class", data=titanic)

"""### pieplot"""

import matplotlib.pyplot as plt

x=[20,60,30]
labels= ['A','B','c']

plt.pie(x=x, labels=labels, autopct='%.1f%%')

"""#3. 데이터 관계 시각화"""

import seaborn as sns
flights = sns.load_dataset("flights")
flights.head()

"""### 히트맵"""

flights_pivot = flights.pivot(index = 'month',
                              columns='year',
                              values='passengers')
flights_pivot

sns.heatmap(data=flights_pivot)

"""### lineplot"""

sns.lineplot(x="year",y="passengers",data = flights)

"""### scatterplot(산점도)


"""

tips = sns.load_dataset("tips")
tips.head()

sns.scatterplot(x= "total_bill", y= "tip", data = tips)

sns.scatterplot(x= "total_bill", y= "tip", hue = "time", data = tips)

"""### regplot(회귀선을 포함한 산점도)"""

sns.regplot(x= "total_bill", y= "tip", data = tips)

sns.regplot(x= "total_bill", y= "tip", ci=99, data = tips)

